/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controllers.*;
import domain.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * make Sure the 1st customer oyu search is the rate that you change
 * 
 */
public class SearchAccountScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form SearchAccountScreen
     */
    BAPACCT bapacct = new BAPACCT();
    BAPCUST bapcust = new BAPCUST();
    public SearchAccountScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        srcAccNoTxtField = new javax.swing.JTextField();
        srcAccNameTxtField = new javax.swing.JTextField();
        srcAccNameButton = new javax.swing.JButton();
        srcAccNoButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        srcPostcodeTxtField = new javax.swing.JTextField();
        srcPostcodeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dcPlnBx = new javax.swing.JFormattedTextField();
        rateTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        srcAccNoTxtField.setText("Search by Account Number");
        srcAccNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcAccNoTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(srcAccNoTxtField);
        srcAccNoTxtField.setBounds(0, 101, 192, 29);

        srcAccNameTxtField.setText("Search by Account Holder's Name");
        srcAccNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcAccNameTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(srcAccNameTxtField);
        srcAccNameTxtField.setBounds(0, 41, 192, 29);

        srcAccNameButton.setText("Search");
        srcAccNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcAccNameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(srcAccNameButton);
        srcAccNameButton.setBounds(40, 70, 85, 29);

        srcAccNoButton.setText("Search");
        srcAccNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcAccNoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(srcAccNoButton);
        srcAccNoButton.setBounds(40, 130, 85, 29);

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(goBackButton);
        goBackButton.setBounds(90, 260, 94, 29);

        jLabel1.setText("Logo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 13, 31, 16);

        srcPostcodeTxtField.setText("Search by Postcode");
        srcPostcodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcPostcodeTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(srcPostcodeTxtField);
        srcPostcodeTxtField.setBounds(0, 160, 192, 29);

        srcPostcodeButton.setText("Search");
        srcPostcodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcPostcodeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(srcPostcodeButton);
        srcPostcodeButton.setBounds(40, 200, 85, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "first name", "last Name", "Discount Plan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(203, 1, 280, 280);

        jButton1.setText("Set/Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 350, 120, 29);

        jLabel8.setText("Discount Plan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 320, 87, 16);
        getContentPane().add(dcPlnBx);
        dcPlnBx.setBounds(50, 350, 131, 26);
        getContentPane().add(rateTextField);
        rateTextField.setBounds(220, 350, 100, 26);

        jLabel2.setText("Rate");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 320, 27, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srcAccNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcAccNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcAccNoTxtFieldActionPerformed

    private void srcAccNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcAccNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcAccNameTxtFieldActionPerformed

    private void srcAccNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcAccNameButtonActionPerformed
           Customer c = bapacct.searchCustomerByName(srcAccNameTxtField);
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();                       
            
            model.addRow(new String []{c.getForename(),c.getSurname(), c.getDiscountType()});
            
            
    }//GEN-LAST:event_srcAccNameButtonActionPerformed

    private void srcAccNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcAccNoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcAccNoButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void srcPostcodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcPostcodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcPostcodeTxtFieldActionPerformed

    private void srcPostcodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcPostcodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcPostcodeButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedRowIndex = jTable1.getSelectedRow();
            
            String plan = model.getValueAt(selectedRowIndex, 2).toString();
          
            dcPlnBx.setText(model.getValueAt(selectedRowIndex, 2).toString());
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Customer c = bapacct.searchCustomerByName(srcAccNameTxtField);
        
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
            int selectedRowIndex = jTable1.getSelectedRow();
            
            String selectedCustomer = model.getValueAt(selectedRowIndex, 0).toString();
            
            float rateSet = Float.valueOf(rateTextField.getText());
            
        //check to see that customer being collected for the discount plan is the same as the 
        // customer that has been selected in the table
        if (c.getForename().equals(selectedCustomer)) {
            bapcust.discountPlanSetFixed(rateSet, c);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "wrong customer selected!");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAccountScreen().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField dcPlnBx;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JButton srcAccNameButton;
    private javax.swing.JTextField srcAccNameTxtField;
    private javax.swing.JButton srcAccNoButton;
    private javax.swing.JTextField srcAccNoTxtField;
    private javax.swing.JButton srcPostcodeButton;
    private javax.swing.JTextField srcPostcodeTxtField;
    // End of variables declaration//GEN-END:variables
}
